In [1]:
%%time
import dask.array as da
import time
import numpy as np

a = da.random.random((30000, 30000), chunks=(1000, 1000))
a

CPU times: user 29.5 ms, sys: 295 ms, total: 324 ms
Wall time: 630 ms


/home/luke/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


dask.array<random_sample, shape=(30000, 30000), dtype=float64, chunksize=(1000, 1000), chunktype=numpy.ndarray>

In [2]:
b = da.random.random((10000, 10000), chunks=(1000, 1000))
b

dask.array<random_sample, shape=(10000, 10000), dtype=float64, chunksize=(1000, 1000), chunktype=numpy.ndarray>

In [3]:
a.dot(b)

/home/luke/anaconda3/lib/python3.9/site-packages/dask/array/routines.py:328: PerformanceWarning: Increasing number of chunks by factor of 10
  intermediate = blockwise(


dask.array<sum-aggregate, shape=(10000, 10000), dtype=float64, chunksize=(1000, 1000), chunktype=numpy.ndarray>

In [4]:
start = time.perf_counter()
a.dot(b).compute()

print(f'Elapsed time: {time.perf_counter() - start} seconds')

/home/luke/anaconda3/lib/python3.9/site-packages/dask/array/routines.py:328: PerformanceWarning: Increasing number of chunks by factor of 10
  intermediate = blockwise(


Elapsed time: 113.07952728300006 seconds


### Comparando com a Numpy

In [ ]:
# Geralmente o kernel morre com essa execução
%%time
a = np.random.rand(20000, 20000)
b = np.random.rand(20000, 20000)

É impossível alocar uma array tão grande com a Numpy, por isso, vamos usar um array menor

In [2]:
%%time
a = np.random.rand(10000, 10000)
b = np.random.rand(10000, 10000)

CPU times: user 348 ms, sys: 489 ms, total: 837 ms
Wall time: 952 ms


Multiplicando um por outro

In [3]:
%%time
# Multiplcar a matriz no numpy
np.matmul(a, b)

CPU times: user 1min 10s, sys: 12.1 s, total: 1min 23s
Wall time: 1min 32s


array([[2524.38470717, 2521.24710571, 2481.33175203, ..., 2510.36092447,
        2507.47473272, 2508.02081047],
       [2516.41575346, 2512.39737418, 2504.26331975, ..., 2518.53551016,
        2505.50944348, 2513.33537315],
       [2515.67338953, 2496.04066566, 2453.20965108, ..., 2495.65551379,
        2479.32206171, 2483.53588209],
       ...,
       [2491.91036537, 2485.51384371, 2468.38311493, ..., 2477.88522297,
        2489.62783134, 2491.14598085],
       [2464.3943329 , 2484.70174916, 2460.45241287, ..., 2491.02217078,
        2467.55270609, 2476.49178382],
       [2501.9129035 , 2496.65596559, 2474.81448588, ..., 2503.5999701 ,
        2493.0863279 , 2495.55941674]])

Agora convertendo para o dask

In [4]:
a = da.from_array(a)
b = da.from_array(b)

In [5]:
%%time
a.dot(b).compute()

CPU times: user 1min 21s, sys: 6.5 s, total: 1min 28s
Wall time: 1min 32s


array([[2524.38470717, 2521.24710571, 2481.33175203, ..., 2510.36092447,
        2507.47473272, 2508.02081047],
       [2516.41575346, 2512.39737418, 2504.26331975, ..., 2518.53551016,
        2505.50944348, 2513.33537315],
       [2515.67338953, 2496.04066566, 2453.20965108, ..., 2495.65551379,
        2479.32206171, 2483.53588209],
       ...,
       [2491.91036537, 2485.51384371, 2468.38311493, ..., 2477.88522297,
        2489.62783134, 2491.14598085],
       [2464.3943329 , 2484.70174916, 2460.45241287, ..., 2491.02217078,
        2467.55270609, 2476.49178382],
       [2501.9129035 , 2496.65596559, 2474.81448588, ..., 2503.5999701 ,
        2493.0863279 , 2495.55941674]])

In [6]:
a = da.random.random((10000, 10000), chunks=(1000, 1000))
b = da.random.random((10000, 10000), chunks=(1000, 1000))

In [7]:
%%time
a.dot(b).compute()

/home/luke/anaconda3/lib/python3.9/site-packages/dask/array/routines.py:328: PerformanceWarning: Increasing number of chunks by factor of 10
  intermediate = blockwise(


CPU times: user 1min 21s, sys: 7.77 s, total: 1min 28s
Wall time: 1min 34s


array([[2468.61748223, 2486.42977384, 2477.95892508, ..., 2492.93058365,
        2497.53480602, 2444.34469514],
       [2507.13940026, 2505.27104762, 2513.54056767, ..., 2513.57130514,
        2518.77907419, 2469.61117599],
       [2479.49038257, 2491.31225365, 2501.50238055, ..., 2497.13871896,
        2521.20404208, 2471.26178499],
       ...,
       [2509.73429893, 2504.33824793, 2508.4380474 , ..., 2520.43467254,
        2531.79006689, 2481.44542899],
       [2481.51218751, 2499.99721249, 2488.81603288, ..., 2504.53421504,
        2515.46669462, 2463.36333929],
       [2474.52074331, 2477.69568103, 2469.13064766, ..., 2488.4981892 ,
        2495.18028115, 2460.19517504]])

Em relação ao tempo, não existe muita diferença, provavelmente pelo tamanho das chunks

In [8]:
a = da.random.random((10000, 10000), chunks=(2000, 2000))
b = da.random.random((10000, 10000), chunks=(2000, 2000))

In [ ]:
%%time
a.dot(b).compute()

Mesmo aumentando o tamanho dos chuncks, não teve diferença nenhuma. Aparentemente a diferença está em gerenciar estruturas grandes

In [ ]:
a = da.random.random((20000, 20000), chunks=(1000, 1000))
b = da.random.random((20000, 20000), chunks=(1000, 1000))

A alocação funciona

In [ ]:
%%time
a.dot(b).compute()